#!/bin/bash

# brrrrrn-ing
prefix=$1

echo "Build the graphs"
if [[ ! -s "$prefix".og ]]; then
  odgi build -g "$prefix".gfa -o "$prefix".og -t 16
fi

if [[ ! -s "$prefix".consensus@10000__y_0_1000000.og ]]; then
  odgi build -g "$prefix".consensus@10000__y_0_1000000.gfa -o "$prefix".consensus@10000__y_0_1000000.og -t 16
fi

echo "Take all path names"
if [[ ! -s "$prefix".all_path_names.txt ]]; then
  odgi paths -i "$prefix".og -L >"$prefix".all_path_names.txt
fi

echo "Take consensus path names"
if [[ ! -s "$prefix".consensus_path_names.txt ]]; then
  grep ^Cons "$prefix".all_path_names.txt >"$prefix".consensus_path_names.txt
fi

echo "Take original path names"
if [[ ! -s "$prefix".original_path_names.txt ]]; then
  grep ^Cons -v "$prefix".all_path_names.txt >"$prefix".original_path_names.txt
fi

echo "Calculate the depth"
if [[ ! -s "$prefix".consensus_path_names.depth.tsv ]]; then
  odgi depth -i "$prefix".og -s "$prefix".original_path_names.txt -R "$prefix".consensus_path_names.txt -t 16 >"$prefix".consensus_path_names.depth.tsv
fi

echo " Remove artifacts and dark matter"
awk '$4 >= 10 && $4 <= 500' "$prefix".consensus_path_names.depth.tsv >"$prefix".consensus_path_names.depth.10_500.tsv

echo "Take the paths touched by the references"
odgi overlap -i "$prefix".og -s "$prefix".consensus_path_names.txt -b <(grep chr8 "$prefix".original_path_names.txt) -t 16 | cut -f 4 >"$prefix".consensus_path_names.touched.txt

echo "Take the link paths between consensus paths that we're saving"
odgi paths -i "$prefix".consensus@10000__y_0_1000000.og -L >"$prefix".consensus@10000__y_0_1000000.path_names.txt

grep ^Link "$prefix".consensus@10000__y_0_1000000.path_names.txt | awk '{ print NR":"$0 }' |
  grep -f <(
    #cat "$prefix".consensus_path_names.touched.txt
    grep ^Link "$prefix".consensus@10000__y_0_1000000.path_names.txt | grep -n -o -Ff <(cut -f 1 "$prefix".consensus_path_names.depth.10_500.tsv) |
    cut -f 1 -d : | sort -n | uniq -c | awk '$1 == 2 { print "^"$2":"} '
  ) |
    cut -f 2 -d : >"$prefix".link_paths.to_extract.txt

echo "Put it all together"
cat <(cut -f 1 "$prefix".consensus_path_names.depth.10_500.tsv) \
  "$prefix".link_paths.to_extract.txt \
  "$prefix".consensus_path_names.touched.txt |
  sort | uniq | awk 'NF > 0' >"$prefix".consensus_path_names.to_extract.txt

echo "Extract"
odgi chop -i "$prefix".consensus@10000__y_0_1000000.og -o "$prefix".consensus@10000__y_0_1000000.chop100.og -c 100 -t 16
odgi extract -i "$prefix".consensus@10000__y_0_1000000.chop100.og -b "$prefix".consensus_path_names.to_extract.txt -c 1 -t 16 -o - | odgi unchop -i - -o "$prefix".consensus@10000__y_0_1000000.brned.og

echo "Get the GFA for Bandage"
odgi view -i "$prefix".consensus@10000__y_0_1000000.brned.og -g >"$prefix".consensus@10000__y_0_1000000.brned.gfa

echo "Bandage"
Bandage image "$prefix".consensus@10000__y_0_1000000.brned.gfa "$prefix".consensus@10000__y_0_1000000.brned.Bandage.h2000nw500linear.png --height 2000 --nodewidth 500 --linear
